version: '3'
services:
  acp_research_api:
    image: ibehave3/acp-research-api:latest
    container_name: acp_research_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://internal_user:password@db:5432/acp_research_db
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
    networks:
      - network
  db:
    container_name: acp_research_db
    image: postgres:13
    ports:
      - "27017:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: internal_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acp_research_db
    networks:
      - network
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.send_redirects=0

networks:
  network:

volumes:
  database_data:
