use diesel::prelude::{Insertable, Queryable};
use serde::{Serialize, Deserialize};

// NOTE: base types -------------------------------
#[derive(Queryable, Serialize, Deserialize, Debug)]
#[diesel(table_name = crate::schema::uhoo_auras)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UhooAura {
    pub id: i32,
    pub userid: i32,
    pub deviceid: String,
    pub virusindex: i32,
    pub temperature: f64,
    pub humidity: f64,
    pub pm25: i32,
    pub tvoc: i32,
    pub co2: i32,
    pub airpressure: f64,
    pub ozone: i32,
    pub no2: i32,
    pub pm1: i32,
    pub pm4: i32,
    pub pm10: i32,
    pub ch2o: i32,
    pub light: i32,
    pub sound: i32,
    pub h2s: i32,
    pub no: i32,
    pub so2: i32,
    pub nh3: i32,
    pub oxygen: i32,
    pub timestamp: i32,
    pub temperatureunit: String,
    pub tempunit: String,
    pub humidityunit: String,
    pub pm25unit: String,
    pub dustunit: String,
    pub tvocunit: String,
    pub vocunit: String,
    pub co2unit: String,
    pub counit: String,
    pub airpressureunit: String,
    pub pressureunit: String,
    pub ozoneunit: String,
    pub no2unit: String,
    pub pm1unit: String,
    pub pm4unit: String,
    pub pm10unit: String,
    pub ch2ounit: String,
    pub lightunit: String,
    pub h2sunit: String,
    pub nounit: String,
    pub so2unit: String,
    pub nh3unit: String,
    pub oxygenunit: String
}

#[derive(Insertable, Serialize, Deserialize, Debug)]
#[diesel(table_name = crate::schema::uhoo_auras)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct CreateUhooAura {
    pub userid: i32,
    pub deviceid: String,
    pub virusindex: i32,
    pub temperature: f64,
    pub humidity: f64,
    pub pm25: i32,
    pub tvoc: i32,
    pub co2: i32,
    pub airpressure: f64,
    pub ozone: i32,
    pub no2: i32,
    pub pm1: i32,
    pub pm4: i32,
    pub pm10: i32,
    pub ch2o: i32,
    pub light: i32,
    pub sound: i32,
    pub h2s: i32,
    pub no: i32,
    pub so2: i32,
    pub nh3: i32,
    pub oxygen: i32,
    pub timestamp: i32,
    pub temperatureunit: String,
    pub tempunit: String,
    pub humidityunit: String,
    pub pm25unit: String,
    pub dustunit: String,
    pub tvocunit: String,
    pub vocunit: String,
    pub co2unit: String,
    pub counit: String,
    pub airpressureunit: String,
    pub pressureunit: String,
    pub ozoneunit: String,
    pub no2unit: String,
    pub pm1unit: String,
    pub pm4unit: String,
    pub pm10unit: String,
    pub ch2ounit: String,
    pub lightunit: String,
    pub h2sunit: String,
    pub nounit: String,
    pub so2unit: String,
    pub nh3unit: String,
    pub oxygenunit: String
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ClientUhooAura {
    pub data: Vec<ClientUhooAuraData>,
    pub usersettings: ClientUhooAuraUserSettings,
    pub sensorlist: Vec<String>,
    pub count: i32,

}

#[derive(Serialize, Deserialize, Debug)]
pub struct ClientUhooAuraData {
    #[serde(rename = "virusIndex")]
    pub virusindex: i32,
    pub temperature: f64,
    pub humidity: f64,
    pub pm25: i32,
    pub tvoc: i32,
    pub co2: i32,
    #[serde(rename = "airPressure")]
    pub airpressure: f64,
    pub ozone: i32,
    pub no2: i32,
    pub pm1: i32,
    pub pm4: i32,
    pub pm10: i32,
    pub ch2o: i32,
    pub light: i32,
    pub sound: i32,
    pub h2s: i32,
    pub no: i32,
    pub so2: i32,
    pub nh3: i32,
    pub oxygen: i32,
    pub timestamp: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ClientUhooAuraUserSettings {
    pub temperature: String,
    pub temp: String,
    pub humidity: String,
    pub pm25: String,
    pub tvoc: String,
    pub co2: String,
    pub co: String,
    #[serde(rename = "airPressure")]
    pub airpressure: String,
    pub pressure: String,
    pub dust: String,
    pub voc: String,
    pub ozone: String,
    pub no2: String,
    pub pm1: String,
    pub pm4: String,
    pub pm10: String,
    pub ch2o: String,
    pub light: String,
    pub h2s: String,
    pub no: String,
    pub so2: String,
    pub nh3: String,
    pub oxygen: String,
}
