-- This file should undo anything in `up.sql`
DROP TABLE gis_locations;
DROP TABLE daily_surveys;
DROP TABLE hourly_surveys;
DROP TABLE fitbit_heartrates;
DROP TABLE fitbit_accelerometers;
DROP TABLE fitbit_barometers;
DROP TABLE fitbit_gyroscopes;
DROP TABLE fitbit_orientations;
DROP TABLE uhoo_business;
DROP TABLE uhoo_homes;
DROP TABLE gray_wolf_sensors;
DROP TABLE gray_wolfs;
DROP TABLE airthings;
DROP TABLE user_airthings;
DROP TABLE user_gray_wolfs;
DROP TABLE user_uhoo_business;
DROP TABLE user_uhoo_homes;
DROP TABLE users;