-- Your SQL goes here
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    username VARCHAR NOT NULL UNIQUE,
    passwordHash VARCHAR NOT NULL,
    salt VARCHAR NOT NULL
);

CREATE TABLE user_airthings (
    id SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    clientSecret VARCHAR NOT NULL,
    clientId VARCHAR NOT NULL,
    groupId VARCHAR NOT NULL,
    deviceIds TEXT[],
    UNIQUE(userId)
);

CREATE TABLE user_gray_wolfs (
    id SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    apiKey VARCHAR NOT NULL,
    deviceIds TEXT[],
    UNIQUE(userId)
);

CREATE TABLE user_uhoo_auras (
    id SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    clientSecret VARCHAR NOT NULL,
    deviceIds TEXT[],
    UNIQUE(userId)
);

CREATE TABLE airthings (
    id SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    battery DOUBLE PRECISION NOT NULL,
    co2 DOUBLE PRECISION NOT NULL,
    humidity DOUBLE PRECISION NOT NULL,
    pm1 DOUBLE PRECISION NOT NULL,
    pm25 DOUBLE PRECISION NOT NULL,
    pressure DOUBLE PRECISION NOT NULL,
    radonShortTermAvg DOUBLE PRECISION NOT NULL,
    temp DOUBLE PRECISION NOT NULL,
    time INT NOT NULL,
    voc DOUBLE PRECISION NOT NULL,
    relayDeviceType VARCHAR NOT NULL
);